spring.application.name=myDefaultSpringBootProject
spring.profiles.active=prod
#spring.data.mongodb.host = localhost
#spring.data.mongodb.port = 27017

#spring.data.mongodb.uri = mongodb+srv://ahmadhassan4714118_db_user:fWEGST9Fn17LRw15@cluster0.dcrpexr.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database = sbDatabase

#spring.data.mongodb.uri=mongodb+srv://ahmadhassan4714118_db_user:fWEGST9Fn17LRw15@cluster0.dcrpexr.mongodb.net/sbDatabase?appName=Cluster0
#spring.data.mongodb.auto-index-creation = true
#server.port=8082


#spring.security.user.name=ahmad
#spring.security.user.password=1234
#server.port=8081


#spring.data.mongodb.username = username
#spring.data.mongodb.password = password