spring.application.name=myProdSpringBootProject

spring.data.mongodb.uri=mongodb+srv://ahmadhassan4714118_db_user:fWEGST9Fn17LRw15@cluster0.dcrpexr.mongodb.net/sbDatabase?appName=Cluster0
spring.data.mongodb.auto-index-creation = true
server.port=8082